export { default as Home } from "./home/home";
export { default as NotFound } from "./not-found/not-found";
export { default as Login } from "./login/login";
export { default as Register } from "./register/register";
export { default as ForgotPassword } from "./forgot-password/forgot-password";
export { default as ResetPassword }  from "./reset-password/reset-password";
export { default as Profile } from "./profile/profile";
export { default as Ingredient } from "./ingredient/ingredient";
export { default as Feed } from "./feed/feed";